---
title: "Single Nuclei vs Single cells (non-depleted) -- Normal tissue, 2 patients"
author: "Sébastien Renaut (sebastien.renaut@criucpq.ulaval.ca)"
date: "`r Sys.time()`"
output:
  html_document:
    number_sections: T
params:
  datapath: 'C:/Users/renseb01/Documents/scRNA/scRNA/data'
  outputpath: '../..' 
---

# Setup  
```{r, setup,echo=FALSE}
knitr::opts_knit$set(root.dir = params$datapath)
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE, cache=FALSE, cache.lazy=FALSE)
```

```{r, requirements}
library(Seurat) #scRNA analyses
library(RColorBrewer)
library(dplyr) #data handling
library(patchwork) #data viz
library(ggplot2) #data viz
library(DT) #data viz
library(plotly)

source('../R/azimuth_analysis.R')

source('../R/infercnv.R')
```


# Loading data  
```{r loading,message  = T, fig.width = 11, fig.height=8,echo=T}  
seurat.objects =readRDS(file.path(params$datapath,"adeno.24samples_27_07_23cnv.rds"))
filenames =  list.files(params$datapath,pattern = '-C[ST]T-',full.names = F)

metadata = read.csv(file.path(params$datapath,"adeno.24samples_metadata.csv"),row.names = 1)
metadata = relabeler(metadata)
```

# 'SingleCells','SingleNuclei','Depleted' specific plots NORMAL
```{r integration,  include= F}
if(file.exists(file.path(params$datapath,'combined_permethod_pertypeT24.rds')) == F){
combined_permethod = list()
for(i in 1:2){
  if(i == 1) samples = c(1:length(filenames))[regexpr('CTT-...._all_',filenames)>0]
  if(i == 2) samples = c(1:length(filenames))[regexpr('CTT-...._SN_',filenames)>0]
 
  combined_permethod[[i]] = merge(seurat.objects[[samples[1]]],seurat.objects[samples[-1]],merge.dr = 'proj.umap')
  
  #features <- SelectIntegrationFeatures(object.list = seurat.objects[samples], nfeatures = 2000)
  #seurat.objects.method <- PrepSCTIntegration(object.list = seurat.objects[samples], anchor.features = features)
  #adeno.anchors <- FindIntegrationAnchors(object.list = seurat.objects.method, normalization.method = "SCT", anchor.features = features)
  #combined_permethod[[i]] <- IntegrateData(anchorset = adeno.anchors, normalization.method = "SCT")
  
  #annotation
  #azimuth_out = azimuth_annotation(combined_permethod[[i]],annotation_threshold = 0.8,v2=T)
  #combined_permethod[[i]] = azimuth_out[[3]]
  
  
  #infercnv
  #infercnv_out = infercnv_wrapper(seurat_obj = combined_permethod[[i]],
  #                          quantile = 0.5, 
  #                          out.dir = file.path(params$datapath,'infercnv/24samples/',ifelse(i==1,'Tumor_cell','Tumor_nucleus')),
  #                          level = 'predicted.ann_level_1',
  #                          gene_order_file = file.path(params$datapath,'gencode.v43.primary_assembly.annotation.positional'))
  
  #combined_permethod[[i]] = infercnv_out[[1]]
  print(paste0('Done ',i,' --- Time is: ', Sys.time()))
}
saveRDS(combined_permethod,file.path(params$datapath,"combined_permethod_pertypeT24.rds"))
} else combined_permethod = readRDS(file.path(params$datapath,'combined_permethod_pertypeT24.rds'))

combined_permethod = relabeler(combined_permethod)

```



# add normal cells to background for UMAP of tumors...
```{r normal background, cell cell type normal tissue}
combined_normaltumor = list()
dimplots = list()

for(k in 1:2){
  if(k == 1) samples = c(1:length(filenames))[regexpr('C.T-...._all_',filenames)>0]
  if(k == 2) samples = c(1:length(filenames))[regexpr('C.T-...._SN_',filenames)>0]
 
  combined_normaltumor[[k]] = merge(seurat.objects[[samples[1]]],seurat.objects[samples[-1]],merge.dr = 'proj.umap')
  combined_normaltumor[[k]] = merge(seurat.objects[[samples[1]]],seurat.objects[samples[-1]],merge.dr = 'proj.umap')
  
  combined_normaltumor = relabeler(combined_normaltumor)
  
  combined_normaltumor[[k]]@meta.data$ann_level1_normal = combined_normaltumor[[k]]@meta.data$predicted.ann_level_1
  combined_normaltumor[[k]]@meta.data$ann_level1_normal[combined_normaltumor[[k]]@meta.data$type == 'Normal'] = 'Normal'
  
  combined_normaltumor[[k]]@meta.data$ann_level1_normal = factor(combined_normaltumor[[k]]@meta.data$ann_level1_normal, levels= c("Endothelial","Epithelial","Immune","Stroma","Unclassified",'Normal'))
  
  dimplots[[k]]=DimPlot(combined_normaltumor[[k]], reduction = "proj.umap", group.by = "ann_level1_normal",cols = c(brewer.pal(n = 5, name = "Set1"),'gray'),pt.size=0.01) + 
    ggtitle(ifelse(k==1,'Cell','Nucleus')) +
    guides(shape='none') + theme(legend.position = "none",axis.title = element_text(size = 8),axis.text = element_text(size = 8),
          axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_blank())
}



   
```

#cell types general plots 
```{r celltypes plots}
barplots_general = list()
for(i in 1:2){
  
  data_summarised = combined_permethod[[i]]@meta.data %>% 
      group_by(predicted.ann_level_1,patient) %>%
      summarise(n = length(predicted.ann_level_1),.groups='keep')

barplots_general[[i]] = ggplot(data=data_summarised, aes(x='', y=n,fill=predicted.ann_level_1)) +
    geom_bar(stat="identity")+scale_fill_manual('Cell Types (level1)',values=c(RColorBrewer::brewer.pal(n = 5, name = "Set1")))+theme_classic()+theme(axis.title = element_text(size = 8),legend.position = ifelse(i ==1,"none",'right')) +ylab('Total Number of cells') + xlab('') 
}



```

```{r stats}
table(metadata$method[metadata$predicted.ann_level_1=='Epithelial' & metadata$type == 'Normal'])
```

# plots
```{r plots}
 pdf(file.path(params$datapath,'../results/Figures_Oct2023/Fig5_UMAPs_CTA_tumor24.pdf'),width = 12,height = 4.5) 
 (dimplots[[1]] + barplots_general[[1]] + dimplots[[2]] + barplots_general[[2]] + plot_layout(widths = c(10,1,10,1))) + plot_annotation(tag_levels = list(c('A','','B')))
dev.off()
```

# plots
```{r lambrechts barplot}
sc_sn_plots = list()
#combined_permethod = readRDS(file.path(params$datapath,'combined_permethod_pertypeN24.rds'))
for(i in 1:2){
metadata_simplified = combined_permethod[[i]]@meta.data
metadata_simplified$patient[metadata_simplified$patient == 4] = 1
metadata_simplified$patient[metadata_simplified$patient == 6] = 2
metadata_simplified$patient[metadata_simplified$patient == 8] = 3
metadata_simplified$patient[metadata_simplified$patient == 10] = 4

#none == unknown
metadata_simplified$predicted.ann_level_3[metadata_simplified$predicted.ann_level_3=='None'] = 'Unclassified'
metadata_simplified$predicted.ann_level_1[metadata_simplified$predicted.ann_level_1=='Unclassified'] = 'Unc'

#filter rare celltypes
celltypes = as.matrix(table(metadata_simplified$predicted.ann_level_3,metadata_simplified$predicted.ann_level_1))


flush = 0
for(c in 1:ncol(celltypes))
{
  rare = rownames(celltypes)[celltypes[,c]<20]
  #filter 
  if(c != ncol(celltypes)) {temp = c(1:nrow(metadata_simplified))[(metadata_simplified$predicted.ann_level_3 %in% rare) & metadata_simplified$predicted.ann_level_1 == colnames(celltypes)[c]]}
  #if(c == ncol(celltypes)) {temp = c(1:nrow(metadata_simplified))[(metadata_simplified$predicted.ann_level_3 == 'unknown') & metadata_simplified$predicted.ann_level_1 == colnames(celltypes)[c]]}
  flush = c(temp,flush)
}

metadata_simplified = metadata_simplified[-flush,]


#shorten names
metadata_simplified$predicted.ann_level_3[metadata_simplified$predicted.ann_level_3=='Lymphatic EC differentiating'] = 'Lymphatic EC diff.'
metadata_simplified$predicted.ann_level_3[metadata_simplified$predicted.ann_level_3=='Lymphatic EC mature'] = 'Lymphatic EC mat.'
metadata_simplified$predicted.ann_level_3[metadata_simplified$predicted.ann_level_3=='Multiciliated lineage'] = 'Multicil. lineage' 
metadata_simplified$predicted.ann_level_3[metadata_simplified$predicted.ann_level_3=='Innate lymphoid cell NK'] = 'Lymphoid cell NK' 

#summarise
data_summarised = metadata_simplified %>% 
  group_by(predicted.ann_level_3,patient,predicted.ann_level_1) %>%
  summarise(n = length(predicted.ann_level_3),sum = sum(nFeature_RNA),cnv_sum = sum(cnv_score),.groups='keep')

data_summarised$n_fraction = 0
data_summarised$nFeature_RNA_mean = 0
data_summarised$cnv_mean = 0
unique_patients = unique(data_summarised$patient)


#keep best labels
for(u in unique(data_summarised$predicted.ann_level_3)){  
  temp = data_summarised[data_summarised$predicted.ann_level_3==u,] 
 
  for(p in seq_along(unique_patients)){
    #this is necessary for the special cases of unknowns which happen in different cell types...
    for(lev1 in c('Immune','Epithelial','Endothelial','Stroma','Unc')){ 
      temp$n_fraction[temp$patient==unique_patients[p] & temp$predicted.ann_level_1 == lev1] = sum(temp$n[temp$patient==unique_patients[p] & temp$predicted.ann_level_1 == lev1]) / sum(temp$n[temp$predicted.ann_level_1==lev1])

      temp$nFeature_RNA_mean[temp$patient==unique_patients[p] & temp$predicted.ann_level_1 == lev1] = sum(temp$sum[temp$patient==unique_patients[p] & temp$predicted.ann_level_1 == lev1])/sum(temp$n[temp$patient==unique_patients[p] & temp$predicted.ann_level_1 == lev1])
 
      temp$cnv_mean[temp$patient==unique_patients[p] & temp$predicted.ann_level_1 == lev1] = sum(temp$cnv_sum[temp$patient==unique_patients[p] & temp$predicted.ann_level_1 == lev1])/sum(temp$n[temp$patient==unique_patients[p] & temp$predicted.ann_level_1 == lev1])
    }
  }
  data_summarised[data_summarised$predicted.ann_level_3 ==u,] = temp
}


data_summarised$predicted.ann_level_1 = factor(data_summarised$predicted.ann_level_1,level = c('Immune','Epithelial','Endothelial','Stroma','Unc'))

data_summarised$patient = factor(data_summarised$patient,level = c(1,2,3,4))

metadata_simplified$predicted.ann_level_1 = factor(metadata_simplified$predicted.ann_level_1,level = c('Immune','Epithelial','Endothelial','Stroma','Unc'))

#plots
fraction_per_patient = ggplot(data_summarised, aes(n_fraction,predicted.ann_level_3,fill = patient)) + 
  geom_col(position = position_fill(reverse = TRUE)) +
    facet_grid(predicted.ann_level_1 ~ ., scales = "free", space = "free",switch = 'y') +
  scale_fill_discrete(type= c(RColorBrewer::brewer.pal(n = 4, name = "Accent"))[4:1]) +
  ylab(paste0('Cell types',ifelse(i==1,' (Cell dataset)',' (Nucleus dataset)'))) +
  xlab('Fraction of cells') +
  theme_bw() + theme(legend.position = ifelse(i==1,'none','bottom'),axis.title.x= list(element_blank(),element_text())[[i]])

number_of_cells = ggplot(data_summarised, aes(n,predicted.ann_level_3 ,fill = patient)) +
     geom_col(position = position_stack(reverse = TRUE)) +
    scale_x_continuous(limits = c(0,ifelse(i==1,15000,12500))) +
    facet_grid(predicted.ann_level_1 ~ ., scales = "free", space = "free",switch = 'y') +
  scale_fill_discrete(type= c(RColorBrewer::brewer.pal(n = 4, name = "Accent"))[4:1]) +
  ylab('clusters') +
  xlab('Number of cells') +
   theme_bw() + theme(legend.position = 'none',strip.background = element_blank(),
  strip.text.y = element_blank(),axis.title.y=element_blank(),axis.text.y=element_blank(),axis.title.x= list(element_blank(),element_text())[[i]])


#data_summarised_UMI = data_summarised[data_summarised$patient=='P4',]
number_of_UMI = ggplot(metadata_simplified, aes(nCount_RNA,predicted.ann_level_3)) + geom_boxplot(fill = "deeppink") + scale_x_continuous(trans= 'log10',breaks = c(500,1500,5000,15000,50000), label = c(500,1500,5000,15000,50000)) +
    facet_grid(predicted.ann_level_1 ~ ., scales = "free", space = "free",switch = 'y') +
  ylab('clusters') +
  xlab('Number of UMIs per cell\n(log scale)') +
   theme_bw() + theme(legend.position = 'none',strip.background = element_blank(),
  strip.text.y = element_blank(),axis.title.y=element_blank(),axis.text.y=element_blank(),axis.title.x= list(element_blank(),element_text())[[i]])

#CNV 
cnvMean = ggplot(metadata_simplified, aes(cnv_score,predicted.ann_level_3)) + geom_boxplot(fill = "aquamarine") + 
  #scale_x_continuous(trans= 'log10',breaks = c(0.0001,0.001,0.01), label = c(0.0001,0.001,0.01),limits = c(0.00004,0.02)) +
  scale_x_continuous(limits = c(0,0.005)) +
    facet_grid(predicted.ann_level_1 ~ ., scales = "free", space = "free",switch = 'y') +
    ylab('clusters') +
    xlab('CNV score') +
    theme_bw() + theme(legend.position = 'none',strip.background = element_blank(),axis.text.y=element_blank(),
                       strip.text.y = element_blank(),axis.title.y=element_blank(),axis.title.x= list(element_blank(),element_text())[[i]])


number_of_genes = ggplot(metadata_simplified, aes(nFeature_RNA,predicted.ann_level_3)) + geom_boxplot(fill = "deeppink") +
    facet_grid(predicted.ann_level_1 ~ ., scales = "free", space = "free",switch = 'y') +
  ylab('clusters') +
  xlab('Number of genes per cell') +
   theme_bw() + theme(legend.position = 'none',strip.background = element_blank(),axis.text.y=element_blank(),
  strip.text.y = element_blank(),axis.title.y=element_blank(),axis.title.x= list(element_blank(),element_text())[[i]])




  sc_sn_plots[[i]] = fraction_per_patient|number_of_cells|number_of_genes|cnvMean
}

pdf(file.path(params$datapath,'../results/Figures_Oct2023/Fig6_barplots_lambrechtsT24.pdf'),width = 14,height = 12) 
(sc_sn_plots[[1]]/sc_sn_plots[[2]] ) + plot_annotation(tag_levels = 'A')
dev.off()
```




```{r done}
print('done')
```

