---
title: "Single Nuclei vs Single cells (non-depleted) -- Normal tissue, 2 patients"
author: "Sébastien Renaut (sebastien.renaut@criucpq.ulaval.ca)"
date: "`r Sys.time()`"
output:
  html_document:
    number_sections: T
params:
  datapath: 'C:/Users/renseb01/Documents/scRNA/scRNA/data'
  outputpath: '../..' 
---

# Setup  
* This are plots for cell type annotations
  
```{r, setup,echo=FALSE}
knitr::opts_knit$set(root.dir = params$datapath)
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE, cache=FALSE, cache.lazy=FALSE)
```

```{r, requirements}
library(Seurat) #scRNA analyses
library(sctransform) #data normalization
library(scater) #outlier values predictions
library(scAnnotatR) #cell type annotation (devtools::install_github('grisslab/scAnnotatR'))
library(DoubletFinder) #find doublets? 

library(vegan) #diversity indices

library(dplyr) #data handling
library(tidyr)
library(patchwork) #data viz
library(ggplot2) #data viz
library(DT) #data viz
library(plotly)
source('../R/doubletfinder.R')
source('../R/azimuth_analysis.R')
```

# Loading data  
```{r loading,message  = T, fig.width = 11, fig.height=8,echo=T}  
seurat.objects =readRDS(file.path(params$datapath,"adeno.12samples.rds"))
filenames =  list.files(params$datapath,pattern = '-C[ST]T-',full.names = F)

metadata = data.frame()
for(i in 1:12)
{
  if(i>1) colnames(metadata) = colnames(seurat.objects[[i]]@meta.data) 
  metadata = rbind(metadata,seurat.objects[[i]]@meta.data)
}

metadata$unique = paste(metadata$method,metadata$type,metadata$patient,sep = '___')

nb_cells_per_sample = as.data.frame(table(metadata$unique),stringsAsFactors = F)
```


# Cell types annotations summaries
```{r celltypes,echo = F} 
data_summarised = metadata %>% 
    group_by(predicted.ann_level_1,method,type,patient,unique) %>%
    summarise(n = length(predicted.ann_level_1),.groups='keep')

data_summarised$fraction = 0

for(i in seq_along(nb_cells_per_sample[,1])){
  data_summarised$fraction[data_summarised$unique == nb_cells_per_sample$Var1[i]] =  data_summarised$n[data_summarised$unique == nb_cells_per_sample$Var1[i]] / nb_cells_per_sample$Freq[i]*100
}

data_summarised$methodXtype = paste(data_summarised$type,data_summarised$method,sep = ' --- ')

summary_bars = ggplot(data=data_summarised, aes(x=patient, y=fraction, fill=predicted.ann_level_1)) +
  geom_bar(stat="identity") + facet_wrap(~methodXtype,nrow = 2, ncol = 3, scales = "free_y") + 
  scale_fill_manual('Cell Types',values=c(RColorBrewer::brewer.pal(n = 5, name = "Set1")))+xlab('Patients')+ylab('Percentage of cells')

summary_bars
pdf(file.path(params$datapath,'../results/Figure2_CTA_general.pdf'),width = 13,height = 7)
summary_bars
dev.off()


#chisquare test (patient, type, method effects)
print('Square test and effect size= -- patient, type, method')
chi = chisq.test(table(metadata$patient,metadata$predicted.ann_level_1))
chi
sqrt(chi$statistic/nrow(metadata))

chi = chisq.test(table(metadata$type,metadata$predicted.ann_level_1))
chi
sqrt(chi$statistic/nrow(metadata))

chi = chisq.test(table(metadata$method,metadata$predicted.ann_level_1))
chi
sqrt(chi$statistic/nrow(metadata))
```


# annotation performance as a function of type, method & level
```{r sandbox}
mean_scores <- metadata %>% group_by(type,method) %>% 
    summarise(level1=mean(predicted.ann_level_1.score),
              level2=mean(predicted.ann_level_2.score),
              level3=mean(predicted.ann_level_3.score),
              level4=mean(predicted.ann_level_4.score),
              finest=mean(predicted.ann_finest_level.score)) %>% pivot_longer(cols = 3:7)

mean_scores$name[mean_scores$name == 'finest'] = 'finest level'

mean_scores$annotation_level = factor(mean_scores$name, level =c('level1','level2','level3','level4','finest level'))

mean_scores = mean_scores[mean_scores$method!='Single Cells (depletion)',]

plot_annot_score<-ggplot(mean_scores, aes(x=type, y=value,group=method)) +
  geom_line(aes(color=method),linetype = "dashed")+
  geom_point(aes(color=method),size = 3) +
  facet_wrap(~annotation_level,nrow = 1, ncol = 5)+
  xlab('Tissue Type') +
  ggtitle('Cell Type Annotation Scores as a function of method, type and annotation level') + ylab('Mean Annotation Score')

plot_annot_score

pdf(file.path(params$datapath,'../results/Figure3_annotation_scores.pdf'),width = 8,height = 5)
plot_annot_score
dev.off()

#statistic test (all effects are significant)
df = metadata %>% pivot_longer(cols =c(15,17,19,21))
print(anova(lm(value~method*type*name,df)))
```


```{r summary T/N finest, message= T}
#how many cell types
dim(metadata %>% 
            group_by(predicted.ann_finest_level) %>%
            summarise(n = length(predicted.ann_finest_level),.groups='keep') %>% 
            filter(n > 100))

#summarise your data
data_summarised = metadata %>% 
  group_by(predicted.ann_level_1,predicted.ann_finest_level,method,type) %>%
  summarise(n = length(predicted.ann_finest_level),.groups='keep') %>% 
  filter(n > 100)

data_summarised$method[data_summarised$method == 'Single Cells'] = 'Single\nCells'
data_summarised$method[data_summarised$method == 'Single Nuclei'] = 'Single\nNuclei'
data_summarised$method[data_summarised$method == 'Single Cells (depletion)'] = 'Single Cells\n(depletion)'

data_summarised$method = factor(data_summarised$method, levels = c('Single\nCells','Single Cells\n(depletion)','Single\nNuclei'))

# Stacked barplot with multiple groups
high_level_colors = c(RColorBrewer::brewer.pal(n = 5, name = "Set1"))
bargplots = list()
bargplots[[1]] = ggplot(data=data_summarised, aes(x=method, y=n, fill=predicted.ann_level_1)) +
  geom_bar(stat="identity") + 
  scale_fill_manual('Cell Types Annotations',values=high_level_colors)+ 
  facet_wrap(~type,nrow = 1, ncol = 2) +
  ggtitle('Cell Types --- coarse annotation') + ylab("Number of Cells")
  
#
celltypes = c('Endothelial','Epithelial','Immune','Stroma')

for(i in seq_along((celltypes)))
  {
  data = data_summarised[data_summarised[,1]==celltypes[i],]
  rgb.palette <- colorRampPalette(c('black',high_level_colors[i], "white"),space = "rgb")
  colors = rgb.palette(length(unique(data$predicted.ann_finest_level))-1)
  colors[length(colors)+1] = 'orange'

  p = ggplot(data=data, aes(x=method, y=n, fill=predicted.ann_finest_level)) +
    geom_bar(stat="identity") +
    scale_fill_manual('Cell Types Annotations',values=colors)+ 
    facet_wrap(~type,nrow = 1, ncol = 2) +
    ggtitle(paste0(celltypes[i],' --- finest level annotation')) + ylab("")

  bargplots[[i+1]] = p
    }

pdf(file.path(params$datapath,'../results/FigureS1_cell_type_annotation_fine_TN.pdf'),width = 20,height = 12)
bargplots[[1]]+(bargplots[[2]]/bargplots[[3]])+(bargplots[[4]]/bargplots[[5]]) + plot_annotation(tag_levels = 'A')
dev.off()
```

# Tumor - normal lineplots
```{r lineplots}
data_summarised = metadata %>% 
  group_by(predicted.ann_level_1,predicted.ann_finest_level,method,type, patient,unique) %>%
  summarise(n = length(predicted.ann_finest_level),.groups='keep')

data_summarised$fraction = 0

data_summarised = data_summarised[data_summarised$predicted.ann_level_1=='Epithelial',]

for(i in seq_along(nb_cells_per_sample[,1])){
  data_summarised$fraction[data_summarised$unique == nb_cells_per_sample$Var1[i]] =  data_summarised$n[data_summarised$unique == nb_cells_per_sample$Var1[i]] / nb_cells_per_sample$Freq[i]*100
}

data_summarised_fraction =  data_summarised %>% 
  group_by(predicted.ann_level_1,predicted.ann_finest_level,method,type) %>%
  summarise(fraction = mean(fraction),.groups='keep')

#plot
lineplots <-ggplot(data_summarised_fraction, aes(x=type, y=fraction, group=method)) +
  geom_line(aes(color=method))+
  geom_point(aes(color=method)) + 
  facet_wrap(~predicted.ann_finest_level,nrow = 4, ncol = 4, scales = "free_y") +
  ggtitle('Epithelial cells - Percentage change Normal / Tumor tissue') + 
  ylab("Percentage of total") +
  xlab("Tissue type")
  
pdf(file.path(params$datapath,paste0('../results/Figure8_epithelial_cells.pdf')),width = 10,height = 6)
lineplots
dev.off()
```


# session info  
```{r session, message= T}
###session
sessionInfo()
```




