---
title: "Single Nuclei vs Single cells (non-depleted) -- Normal tissue, 2 patients"
author: "Sébastien Renaut (sebastien.renaut@criucpq.ulaval.ca)"
date: "`r Sys.time()`"
output:
  html_document:
    number_sections: T
params:
  datapath: 'C:/Users/renseb01/Documents/scRNA/scRNA/data'
  outputpath: '../..' 
---

# Setup  
```{r, setup,echo=FALSE}
knitr::opts_knit$set(root.dir = params$datapath)
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE, cache=FALSE, cache.lazy=FALSE)
```

```{r, requirements}
library(Seurat) #scRNA analyses
library(sctransform) #data normalization
library(scater) #outlier values predictions
library(scAnnotatR) #cell type annotation (devtools::install_github('grisslab/scAnnotatR'))
library(DoubletFinder) #find doublets? 
library(RColorBrewer)
library(vegan) #diversity indices

library(readxl)
library(dplyr) #data handling
library(tidyr)
library(patchwork) #data viz
library(ggplot2) #data viz
library(DT) #data viz
library(plotly)
source('../R/doubletfinder.R')
source('../R/azimuth_analysis.R')
```

# Loading data  
```{r loading,message  = T, fig.width = 11, fig.height=8,echo=T}  
seurat.objects =readRDS(file.path(params$datapath,"adeno.12samples.rds"))
filenames =  list.files(params$datapath,pattern = '-C[ST]T-',full.names = F)

metadata = data.frame()
cells = NULL
for(i in 1:12)
{
  if(i>1) colnames(metadata) = colnames(seurat.objects[[i]]@meta.data) 
  metadata = rbind(metadata,seurat.objects[[i]]@meta.data)
  cells[i] = median(seurat.objects[[i]]@meta.data$nFeature_RNA)
}

metadata$unique = paste(metadata$method,metadata$type,metadata$patient,sep = '___')

nb_cells_per_sample = as.data.frame(table(metadata$unique),stringsAsFactors = F)
```






# 'SingleCells','SingleNuclei','Depleted' specific plots NORMAL
```{r UMAPplots}
if(file.exists(file.path(params$datapath,'combined_depletion_pertissue.rds')) == F){
npc=30
type = c('Normal','Tumor')
combined_permethod = list()
for(i in seq_along(type)){
  if(i == 1) samples = c(1:length(filenames))[regexpr('CST-...._depletion_',filenames)>0]
  if(i == 2) samples = c(1:length(filenames))[regexpr('CTT-...._depletion_',filenames)>0]
 #if((i == 3)&(t==1)) samples = c(1:length(filenames))[regexpr('CST-...._depletion_',filenames)>0]
  
  features <- SelectIntegrationFeatures(object.list = seurat.objects[samples], nfeatures = 2000)
  seurat.objects.method <- PrepSCTIntegration(object.list = seurat.objects[samples], anchor.features = features)
  adeno.anchors <- FindIntegrationAnchors(object.list = seurat.objects.method, normalization.method = "SCT", anchor.features = features)
  combined_permethod[[i]] <- IntegrateData(anchorset = adeno.anchors, normalization.method = "SCT")
  combined_permethod[[i]] <- RunPCA(combined_permethod[[i]], verbose = FALSE)
  combined_permethod[[i]] <- RunUMAP(combined_permethod[[i]], reduction = "pca", dims = 1:npc, verbose = FALSE)
  combined_permethod[[i]]@meta.data$level1_type = paste(substring(combined_permethod[[i]]@meta.data$predicted.ann_level_1,1,4),combined_permethod[[i]]@meta.data$type,sep = '_')
  
  combined_permethod[[i]] <- FindNeighbors(combined_permethod[[i]], reduction = "pca", dims = 1:30)
  combined_permethod[[i]] <- FindClusters(combined_permethod[[i]], resolution = 0.5)
}
saveRDS(combined_permethod,file.path(params$datapath,"combined_depletion_pertissue.rds"))
} else combined_permethod = readRDS(file.path(params$datapath,'combined_depletion_pertissue.rds'))

```

#cell types & UMAPs
```{r celltypes plots}
barplots_general = list()
for(i in 1:2){
  
  data_summarised = combined_permethod[[i]]@meta.data %>% 
      group_by(predicted.ann_level_1,patient) %>%
      summarise(n = length(predicted.ann_level_1),.groups='keep')

barplots_general[[i]] = ggplot(data=data_summarised, aes(x='', y=n,fill=predicted.ann_level_1)) +
    geom_bar(stat="identity")+scale_fill_manual('Cell Types',values=c(RColorBrewer::brewer.pal(n = 5, name = "Set1")))+theme_classic()+theme(axis.title = element_text(size = 8),legend.position = ifelse(i ==1,"none",'right')) +ylab('Total Number of cells') + xlab('') 
}

plot_UMAPS = list()
###plots
  plot_depletion_N=DimPlot(combined_permethod[[1]], reduction = "umap", group.by = "predicted.ann_level_1",cols = brewer.pal(n = 5, name = "Set1"),pt.size=0.4) + ggtitle('immune depleted cells --- Normal') + guides(shape='none') +theme(legend.position = "none",axis.title = element_text(size = 8),axis.text =element_text(size = 8) )
   plot_depletion_N$labels$colour = 'Cell types'  
   
   
  plot_depletion_T=DimPlot(combined_permethod[[2]], reduction = "umap", group.by = "predicted.ann_level_1",cols = brewer.pal(n = 5, name = "Set1"),pt.size=0.4) + ggtitle('immune depleted cells --- Tumor') + guides(shape='none') +theme(legend.position = "none",axis.title = element_text(size = 8),axis.text =element_text(size = 8))
  plot_depletion_T$labels$colour = 'Cell types'  

```


# STRESS ANALYSIS
```{r loadRDS,message  = T,echo=T}  
stress_references = read_xlsx(file.path(params$datapath,"512genes_OFlanagan_et_al2019.xlsx"))

#prepare output df
stress_genes = data.frame(gene = rownames(seurat.objects[[i]]@assays$RNA[rownames(seurat.objects[[i]]@assays$RNA) %in% stress_references$gene_symbol,]))


for(i in 1:12){
  temp  = seurat.objects[[i]]@assays$RNA[rownames(seurat.objects[[i]]@assays$RNA) %in% stress_references$gene_symbol,]
  temp2 = NULL

  for(j in 1:nrow(temp)){
    temp2 = c(temp2,length(temp[j,temp[j,]>0])/ncol(temp))
    }
  stress_genes = cbind(stress_genes,temp2)
}
#
colnames(stress_genes)[-1] = filenames
stress_genes = stress_genes %>%
    pivot_longer(!gene, names_to = "filnames")

#
stress_genes$method  = '0'
stress_genes$type = '0'
stress_genes$patient = '0'

stress_genes$type = ifelse(regexpr('CST',stress_genes$filnames)>0,'Normal','Tumor')
stress_genes$method[regexpr('_SN_',stress_genes$filnames)>0] = 'Nuclei'
stress_genes$method[regexpr('_all_',stress_genes$filnames)>0] = 'Cells'
stress_genes$method[regexpr('_depletion_',stress_genes$filnames)>0] = 'Immune\ndepleted cells'
stress_genes$patient = ifelse(regexpr('^4',stress_genes$filnames)>0,'P4','P6')
stress_genes$sqrt = stress_genes$value**0.5

#statistical tests
anova(lm(value~method*type+patient, data = stress_genes))

stress_genes %>% 
  group_by(type,method) %>%
  summarise(n = median(value,na.rm =T),.groups='keep') 

stress_genes %>% 
  group_by(type) %>%
  summarise(n = median(value,na.rm =T),.groups='keep') 

stress_genes %>% 
  group_by(method) %>%
  summarise(n = median(value,na.rm =T),.groups='keep') 

###plot
p_method = ggplot(stress_genes, aes(x=method, y=value, fill=method)) +
  geom_boxplot(position="dodge",outlier.shape = NA) +
  ylab("mean % of cells expressing a stress-related gene")  +
  theme(axis.text.x = element_text(size=7))

p_type = ggplot(stress_genes, aes(x=type, y=value, fill=type)) +
  geom_boxplot(position="dodge",outlier.shape = NA) +
  scale_fill_manual(values = c('yellow','darkblue')) +
  ylab("")

p_patient = ggplot(stress_genes, aes(x=patient, y=value, fill=patient)) +
  geom_boxplot(position="dodge",outlier.shape = NA) +
  ylab('')

p_method_type = ggplot(stress_genes, aes(x=method, y=value, fill=method)) +
  geom_boxplot(position="dodge",outlier.shape = NA) +
  ylab("mean % of cells expressing\na stress-related gene")  +
  facet_wrap(~type)+
  theme(axis.text.x = element_text(size=7))

```  

# Cell types annotations summaries
```{r celltypes,echo = F} 
data_summarised = metadata %>% 
    group_by(predicted.ann_level_1,method,type,patient,unique) %>%
    summarise(n = length(predicted.ann_level_1),.groups='keep')

data_summarised$fraction = 0
data_summarised$method[data_summarised$method == 'Single Cells'] = 'Cells'
data_summarised$method[data_summarised$method == 'Single Nuclei'] = 'Nuclei'
data_summarised$method[data_summarised$method == 'Single Cells (depletion)'] = 'Immune depleted\ncells'
for(i in seq_along(nb_cells_per_sample[,1])){
  data_summarised$fraction[data_summarised$unique == nb_cells_per_sample$Var1[i]] =  data_summarised$n[data_summarised$unique == nb_cells_per_sample$Var1[i]] / nb_cells_per_sample$Freq[i]*100
}

data_summarised$methodXtype = paste(data_summarised$type,data_summarised$method,sep = ' --- ')

summary_bars = ggplot(data=data_summarised, aes(x=patient, y=fraction, fill=predicted.ann_level_1)) +
  geom_bar(stat="identity") + facet_wrap(~interaction(method,type,sep = " --- "),nrow = 2, ncol = 3, scales = "free_y") + 
  scale_fill_manual('Cell Types',values=c(RColorBrewer::brewer.pal(n = 5, name = "Set1")))+xlab('Patients')+ylab('Percentage of cells')
```


```{r save plots, message= T}
empty_placeholder = ggplot() + theme_void()
###plots
  
  pdf(file.path(params$datapath,'../results/UMAPs_depletion.pdf'),width = 12,height = 7) 
 (plot_depletion_N + barplots_general[[1]] + plot_depletion_T + barplots_general[[2]] + plot_layout(widths = c(10,1,10,1))) / 
 
  (p_method_type + summary_bars + plot_layout(widths = c(9,13))) + plot_annotation(tag_levels = list(c('A','','B','','C','D','')))
  dev.off()
```

# session info  
```{r session, message= T}
###session
sessionInfo()
```


