---
title: "Single Nuclei vs Single cells (non-depleted) -- Normal tissue, 2 patients"
author: "Sébastien Renaut (sebastien.renaut@criucpq.ulaval.ca)"
date: "`r Sys.time()`"
output:
  html_document:
    number_sections: T
params:
  datapath: 'C:/Users/renseb01/Documents/scRNA/scRNA/data'
  outputpath: '../..' 
---

# Setup  
```{r, setup,echo=FALSE}
knitr::opts_knit$set(root.dir = params$datapath)
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE, cache=FALSE, cache.lazy=FALSE)
```

```{r, requirements}
library(Seurat) #scRNA analyses
library(sctransform) #data normalization
library(scater) #outlier values predictions
library(scAnnotatR) #cell type annotation (devtools::install_github('grisslab/scAnnotatR'))
library(DoubletFinder) #find doublets? 
library(RColorBrewer)
library(vegan) #diversity indices

library(dplyr) #data handling
library(patchwork) #data viz
library(ggplot2) #data viz
library(DT) #data viz
library(plotly)
source('../R/doubletfinder.R')
source('../R/azimuth_analysis.R')
```

# Loading data  
```{r loading,message  = T, fig.width = 11, fig.height=8,echo=T}  
seurat.objects =readRDS(file.path(params$datapath,"adeno.12samples.rds"))
filenames =  list.files(params$datapath,pattern = '-C[ST]T-',full.names = F)

metadata = data.frame()
cells = NULL
for(i in 1:12)
{
  if(i>1) colnames(metadata) = colnames(seurat.objects[[i]]@meta.data) 
  metadata = rbind(metadata,seurat.objects[[i]]@meta.data)
  cells[i] = median(seurat.objects[[i]]@meta.data$nFeature_RNA)
}

metadata$unique = paste(metadata$method,metadata$type,metadata$patient,sep = '___')

nb_cells_per_sample = as.data.frame(table(metadata$unique),stringsAsFactors = F)
```






# 'SingleCells','SingleNuclei','Depleted' specific plots NORMAL
```{r UMAPplots}
if(file.exists(file.path(params$datapath,'combined_permethod_pertypeT.rds')) == F){
npc=30
type = c('Tumor')
combined_permethod = list()
for(i in 1:2){
  if((i == 1) & (type == 'Tumor')) samples = c(1:length(filenames))[regexpr('CTT-...._all_',filenames)>0]
  if((i == 2) & (type == 'Tumor')) samples = c(1:length(filenames))[regexpr('CTT-...._SN_',filenames)>0]
 #if((i == 3)&(t==1)) samples = c(1:length(filenames))[regexpr('CST-...._depletion_',filenames)>0]
  
  features <- SelectIntegrationFeatures(object.list = seurat.objects[samples], nfeatures = 2000)
  seurat.objects.method <- PrepSCTIntegration(object.list = seurat.objects[samples], anchor.features = features)
  adeno.anchors <- FindIntegrationAnchors(object.list = seurat.objects.method, normalization.method = "SCT", anchor.features = features)
  combined_permethod[[i]] <- IntegrateData(anchorset = adeno.anchors, normalization.method = "SCT")
  combined_permethod[[i]] <- RunPCA(combined_permethod[[i]], verbose = FALSE)
  combined_permethod[[i]] <- RunUMAP(combined_permethod[[i]], reduction = "pca", dims = 1:npc, verbose = FALSE)
  combined_permethod[[i]]@meta.data$level1_type = paste(substring(combined_permethod[[i]]@meta.data$predicted.ann_level_1,1,4),combined_permethod[[i]]@meta.data$type,sep = '_')
  
  combined_permethod[[i]] <- FindNeighbors(combined_permethod[[i]], reduction = "pca", dims = 1:30)
  combined_permethod[[i]] <- FindClusters(combined_permethod[[i]], resolution = 0.5)
}
saveRDS(combined_permethod,file.path(params$datapath,"combined_permethod_pertypeT.rds"))
} else combined_permethod = readRDS(file.path(params$datapath,'combined_permethod_pertypeT.rds'))

```

# 'SingleCells','SingleNuclei' NORMAL subset epit & Immune
```{r per method, cell cell type normal tissue}
if(file.exists(file.path(params$datapath,'combined_permethod_percelltypeT.rds')) == F){
npc=30
type = c('Tumor')
cell_type = c('Epithelial','Immune')
seurat.objects.cell_type = list(seurat.objects,seurat.objects)
combined_permethod_percelltype = list(list(),list())
#subsetting epi and immune
for(c in seq_along(cell_type)){
for(f in seq_along(filenames)){
    seurat.objects.cell_type[[c]][[f]] = subset(seurat.objects.cell_type[[c]][[f]],subset = predicted.ann_level_1 == cell_type[c])
  }}


#integration
for(c in seq_along(cell_type)){

for(i in 1:2){
  if((i == 1) & (type == 'Tumor')) samples = c(1:length(filenames))[regexpr('CTT-...._all_',filenames)>0]
  if((i == 2) & (type == 'Tumor')) samples = c(1:length(filenames))[regexpr('CTT-...._SN_',filenames)>0]
  
  features <- SelectIntegrationFeatures(object.list = seurat.objects.cell_type[[c]][samples], nfeatures = 2000)
  seurat.objects.method <- PrepSCTIntegration(object.list = seurat.objects.cell_type[[c]][samples], anchor.features = features)
  adeno.anchors <- FindIntegrationAnchors(object.list = seurat.objects.method, normalization.method = "SCT", anchor.features = features)
  combined_permethod_percelltype[[c]][[i]] <- IntegrateData(anchorset = adeno.anchors, normalization.method = "SCT")
  combined_permethod_percelltype[[c]][[i]] <- RunPCA(combined_permethod_percelltype[[c]][[i]], verbose = FALSE)
  combined_permethod_percelltype[[c]][[i]] <- RunUMAP(combined_permethod_percelltype[[c]][[i]], reduction = "pca", dims = 1:npc, verbose = FALSE)
  combined_permethod_percelltype[[c]][[i]] <- FindNeighbors(combined_permethod_percelltype[[c]][[i]], reduction = "pca", dims = 1:30)
  combined_permethod_percelltype[[c]][[i]] <- FindClusters(combined_permethod_percelltype[[c]][[i]], resolution = 0.5)
  
  # for annotation's sake, label cells with freq < 1% as 'others' (per sample)
 fine_annotations_summary = table(combined_permethod_percelltype[[c]][[i]]@meta.data$predicted.ann_finest_level)
 others = names(fine_annotations_summary)[fine_annotations_summary<45]
  combined_permethod_percelltype[[c]][[i]]@meta.data$predicted.ann_finest_level[combined_permethod_percelltype[[c]][[i]]@meta.data$predicted.ann_finest_level %in% others] = 'others'
  

  #fixed the names
combined_permethod_percelltype[[c]][[i]]@meta.data$predicted.ann_finest_level = ifelse(nchar(combined_permethod_percelltype[[c]][[i]]@meta.data$predicted.ann_finest_level)>12,sub(" ([^ ]*)$", "\n\\1",combined_permethod_percelltype[[c]][[i]]@meta.data$predicted.ann_finest_level),combined_permethod_percelltype[[c]][[i]]@meta.data$predicted.ann_finest_level)
  
}}

saveRDS(combined_permethod_percelltype,file.path(params$datapath,"combined_permethod_percelltypeT.rds"))
} else combined_permethod_percelltype = readRDS(file.path(params$datapath,'combined_permethod_percelltypeT.rds'))
```

# 'SingleCells','SingleNuclei' NORMAL subset epit & ImmunePLOTS
```{r UMAPplots}
###plots
barplots = list()

cell_type = c('Epithelial','Immune')
for(c in seq_along(cell_type)){

  all_types = c(combined_permethod_percelltype[[c]][[1]]@meta.data$predicted.ann_finest_level,
  combined_permethod_percelltype[[c]][[2]]@meta.data$predicted.ann_finest_level)
  all_types = names(table(all_types))
  all_colors = c(brewer.pal(n =12, name = "Paired"),'gray','black','darkred')[1:length(all_types)]
  all_colors_type = data.frame(all_types,all_colors)
  
for(i in 1:2){
#cell types plots  FINE LEVELS
  data_summarised = combined_permethod_percelltype[[c]][[i]]@meta.data %>% 
      group_by(predicted.ann_finest_level,patient) %>%
      summarise(n = length(predicted.ann_level_1),.groups='keep')
  
  if(i == 2 & c == 2) {data_summarised = data_summarised %>% bind_rows(data.frame(predicted.ann_finest_level= c("B cells","CD4 T cells","CD8 T cells","Classical\nmonocytes","DC2","Interstitial Mφ\nperivascular","Mast cells","Monocyte-derived\nMφ","NK cells","Non-classical\nmonocytes"),patient = rep('P4',10),n =rep(0,10) ))}
  
  
  if(i == 2 & c == 1) {data_summarised = data_summarised %>% bind_rows(data.frame(predicted.ann_finest_level= c("Goblet\n(nasal)"),patient = 'P4',n =0))}
  
  color_vector = all_colors_type$all_colors[all_colors_type$all_types %in% unique(data_summarised$predicted.ann_finest_level)]
  
  #data_summarised$fraction = 0
  #data_summarised$fraction[data_summarised$patient== 'P4'] = data_summarised$n[data_summarised$patient== 'P4']/sum(data_summarised$n[data_summarised$patient== 'P4'])*100
  
  #data_summarised$fraction[data_summarised$patient== 'P6'] = data_summarised$n[data_summarised$patient== 'P6']/sum(data_summarised$n[data_summarised$patient== 'P6'])*100

barplots[[(i*2)+c-2]] = ggplot(data=data_summarised, aes(x='', y=n,fill=predicted.ann_finest_level)) +
    geom_bar(stat="identity")+scale_fill_manual( ifelse(c==1,'Epithelial','Immune'),values=color_vector) + ylab('Total Number of Cells')+theme_classic() + xlab('')+theme(axis.title = element_text(size = 8),legend.position = ifelse(i ==1,"none",'right'))

}}

```


#cell types general plots 
```{r celltypes plots}
barplots_general = list()
for(i in 1:2){
  
  data_summarised = combined_permethod[[i]]@meta.data %>% 
      group_by(predicted.ann_level_1,patient) %>%
      summarise(n = length(predicted.ann_level_1),.groups='keep')

 # data_summarised$fraction = 0
  
#  data_summarised$fraction[data_summarised$patient== 'P4'] = data_summarised$n[data_summarised$patient== 'P4']/sum(data_summarised$n[data_summarised$patient== 'P4'])*100
  
#  data_summarised$fraction[data_summarised$patient== 'P6'] = data_summarised$n[data_summarised$patient== 'P6']/sum(data_summarised$n[data_summarised$patient== 'P6'])*100

barplots_general[[i]] = ggplot(data=data_summarised, aes(x='', y=n,fill=predicted.ann_level_1)) +
    geom_bar(stat="identity")+scale_fill_manual('Cell Types',values=c(RColorBrewer::brewer.pal(n = 5, name = "Set1")))+theme_classic()+theme(axis.title = element_text(size = 8),legend.position = ifelse(i ==1,"none",'right')) +ylab('Total Number of cells') + xlab('') 
}
```



# plots
```{r plots}
plot_UMAPS = list()
###plots
  plot_SC=DimPlot(combined_permethod[[1]], reduction = "umap", group.by = "predicted.ann_level_1",cols = brewer.pal(n = 5, name = "Set1"),pt.size=0.4) + ggtitle('Cells') + guides(shape='none') +theme(legend.position = "none",axis.title = element_text(size = 8),axis.text =element_text(size = 8) )
   plot_SC$labels$colour = 'Cell types'  
   
   
  plot_SN=DimPlot(combined_permethod[[2]], reduction = "umap", group.by = "predicted.ann_level_1",cols = brewer.pal(n = 5, name = "Set1"),pt.size=0.4) + ggtitle('Nuclei') + guides(shape='none') +theme(legend.position = "none",axis.title = element_text(size = 8),axis.text =element_text(size = 8))
  plot_SN$labels$colour = 'Cell types'  

  
###plots
for(c in seq_along(cell_type)){

  all_types = c(combined_permethod_percelltype[[c]][[1]]@meta.data$predicted.ann_finest_level,
  combined_permethod_percelltype[[c]][[2]]@meta.data$predicted.ann_finest_level)
  all_types = names(table(all_types))
  all_colors = c(brewer.pal(n =12, name = "Paired"),'gray','black','darkred')[1:length(all_types)]
  all_colors_type = data.frame(all_types,all_colors)
  
for(i in 1:2){
#cell types plots  FINE LEVELS
  data_summarised = combined_permethod_percelltype[[c]][[i]]@meta.data %>% 
      group_by(predicted.ann_finest_level,patient) %>%
      summarise(n = length(predicted.ann_level_1),.groups='keep')
  
  color_vector = all_colors_type$all_colors[all_colors_type$all_types %in% unique(data_summarised$predicted.ann_finest_level)]
  
  
  title = paste0(ifelse(c==1,'Epithelial --- ','Immune --- '),ifelse(i==1,'Cells','Nuclei'))
  #
  plot_UMAPS[[(i*2)+c-2]] = DimPlot(combined_permethod_percelltype[[c]][[i]], reduction = "umap", cols = color_vector,group.by = "predicted.ann_finest_level",pt.size=1) + ggtitle(title) + guides(shape='none') + theme(legend.text=element_text(size=7),legend.position='none',axis.title = element_text(size = 8),axis.text =element_text(size = 8))
  #plot_UMAPS[[(i*2)+c-2]]$labels$colour = ifelse(c==1,'Epithelial','Immune') 
}}
 
  
  pdf(file.path(params$datapath,'../results/UMAPs_CTA_tumor.pdf'),width = 12,height = 7) 
 (plot_SC + barplots_general[[1]] + plot_SN + barplots_general[[2]] + plot_layout(widths = c(10,1,10,1))) / 
 (plot_UMAPS[[2]] + barplots[[2]] + plot_UMAPS[[4]] + (barplots[[4]]+guides(fill=guide_legend(ncol=2))) + plot_layout(widths = c(10,1,10,1)))  / (plot_UMAPS[[1]] + barplots[[1]] + plot_UMAPS[[3]] + (barplots[[3]]+guides(fill=guide_legend(ncol=2))) + plot_layout(widths = c(10,1,10,1))) + plot_annotation(tag_levels = list(c('A','','','','B','','','','C','','','')))
  dev.off()
```



```{r lambrechts barplot}
sc_sn_plots = list()
for(i in 1:2){

data_summarised = combined_permethod[[i]]@meta.data %>% 
  group_by(integrated_snn_res.0.5,patient,predicted.ann_level_1) %>%
  summarise(n = length(integrated_snn_res.0.5),sum = sum(nFeature_RNA),.groups='keep')

data_summarised$n_fraction = 0
data_summarised$best_label = ''
data_summarised$nFeature_RNA_mean = 0
data_summarised$most_probable_name = ''

#keep best labels
for(u in unique(data_summarised$integrated_snn_res.0.5)){  
  temp = data_summarised[data_summarised$integrated_snn_res.0.5==u,] 
  temp$best_label = temp$predicted.ann_level_1[temp$n==max(temp$n)]
  temp$n_fraction[temp$patient=='P4'] = sum(temp$n[temp$patient=='P4'])/sum(temp$n)
  temp$n_fraction[temp$patient=='P6'] = sum(temp$n[temp$patient=='P6'])/sum(temp$n)
  temp$nFeature_RNA_mean[temp$patient=='P4'] = sum(temp$sum[temp$patient=='P4'])/sum(temp$n[temp$patient=='P4'])
   temp$nFeature_RNA_mean[temp$patient=='P6'] = sum(temp$sum[temp$patient=='P6'])/sum(temp$n[temp$patient=='P6'])
  data_summarised[data_summarised$integrated_snn_res.0.5==u,] = temp
  
  
  #most probable name
  temp2 = table(combined_permethod[[i]]@meta.data$predicted.ann_finest_level[combined_permethod[[i]]$integrated_snn_res.0.5==u])
  most_probable_name = names(temp2)[temp2== max(temp2)][1]
  data_summarised$most_probable_name[data_summarised$integrated_snn_res.0.5==u & data_summarised$patient=='P4'] = most_probable_name
  
}

data_summarised = data_summarised[data_summarised$predicted.ann_level_1==data_summarised$best_label,]
data_summarised$integrated_snn_res.0.5= factor(data_summarised$integrated_snn_res.0.5,level = c(max(as.numeric(data_summarised$integrated_snn_res.0.5)):0))
data_summarised$predicted.ann_level_1 = factor(data_summarised$predicted.ann_level_1,level = c('Immune','Epithelial','Endothelial','Stroma','unknown'))

fraction_per_patient = ggplot(data_summarised, aes(n_fraction,integrated_snn_res.0.5,fill = patient)) + 
  geom_col() +
  geom_text(aes(x=1,label = most_probable_name,hjust = 'right'),size =4) +
    facet_grid(predicted.ann_level_1 ~ ., scales = "free", space = "free",switch = 'y') +
  ylab('clusters') +
  xlab('Fraction of cells') +
  theme_bw() + theme(legend.position = ifelse(i==1,'none','bottom'),axis.title.x= list(element_blank(),element_text())[[i]])


number_of_cells = ggplot(data_summarised, aes(n,integrated_snn_res.0.5,fill = patient)) +
    geom_col() +
    facet_grid(predicted.ann_level_1 ~ ., scales = "free", space = "free",switch = 'y') +
  ylab('clusters') +
  xlab('Number of cells') +
   theme_bw() + theme(legend.position = 'none',strip.background = element_blank(),
  strip.text.y = element_blank(),axis.title.y=element_blank(),axis.title.x= list(element_blank(),element_text())[[i]])


#data_summarised_UMI = data_summarised[data_summarised$patient=='P4',]
number_of_UMI = ggplot(data_summarised, aes(nFeature_RNA_mean,integrated_snn_res.0.5,col = patient)) +
    geom_point(size=4) +
    facet_grid(predicted.ann_level_1 ~ ., scales = "free", space = "free",switch = 'y') +
  ylab('clusters') +
  xlab('Mean number of UMIs per cell') +
   theme_bw() + theme(legend.position = 'none',strip.background = element_blank(),
  strip.text.y = element_blank(),axis.title.y=element_blank(),axis.title.x= list(element_blank(),element_text())[[i]])


  sc_sn_plots[[i]] = fraction_per_patient+number_of_cells+number_of_UMI

  
}
pdf(file.path(params$datapath,'../results/barplots_lambrechtsT.pdf'),width = 12,height = 10) 
(sc_sn_plots[[1]]/sc_sn_plots[[2]] ) + plot_annotation(tag_levels = 'A')
dev.off()
```



# session info  
```{r session, message= T}
###session
sessionInfo()
```

