---
title: "Single Nuclei vs Single cells (non-depleted) -- Normal tissue, 2 patients"
author: "Sébastien Renaut (sebastien.renaut@criucpq.ulaval.ca)"
date: "`r Sys.time()`"
output:
  html_document:
    number_sections: T
params:
  datapath: 'C:/Users/renseb01/Documents/scRNA/scRNA/data'
  outputpath: '../..' 
---

```{r, setup,echo=FALSE}
knitr::opts_knit$set(root.dir = params$datapath)
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE, cache=FALSE, cache.lazy=FALSE)
```

```{r, requirements}
#requirements
library(dplyr)
library(ggplot2)
library(patchwork)
library(Seurat)
library(readxl)
```

# Loading data  
```{r loadRDS,message  = T,echo=T}  
seurat.objects = readRDS(file.path(params$datapath,"adeno.12samples.rds"))
stress_references = read_xlsx(file.path(params$datapath,"512genes_OFlanagan_et_al2019.xlsx"))

#prepare output df
stress_genes = data.frame(gene = rownames(seurat.objects[[i]]@assays$RNA[rownames(seurat.objects[[i]]@assays$RNA) %in% stress_references$gene_symbol,]))


for(i in 1:12){
  temp  = seurat.objects[[i]]@assays$RNA[rownames(seurat.objects[[i]]@assays$RNA) %in% stress_references$gene_symbol,]
  temp2 = NULL

  for(j in 1:nrow(temp)){
    temp2 = c(temp2,length(temp[j,temp[j,]>0])/ncol(temp))
    }
  stress_genes = cbind(stress_genes,temp2)
}
#
colnames(stress_genes)[-1] = filenames
stress_genes = stress_genes %>%
    pivot_longer(!gene, names_to = "filnames")

#
stress_genes$method  = '0'
stress_genes$type = '0'
stress_genes$patient = '0'

stress_genes$type = ifelse(regexpr('CST',stress_genes$filnames)>0,'Normal','Tumor')
stress_genes$method[regexpr('_SN_',stress_genes$filnames)>0] = 'Single Nuclei'
stress_genes$method[regexpr('_all_',stress_genes$filnames)>0] = 'Single Cells'
stress_genes$method[regexpr('_depletion_',stress_genes$filnames)>0] = 'Single Cells\n(depleted)'
stress_genes$patient = ifelse(regexpr('^4',stress_genes$filnames)>0,'P4','P6')
stress_genes$sqrt = stress_genes$value**0.5
```

```{r stat tests}
#statistical tests
anova(lm(value~method*type+patient, data = stress_genes))

stress_genes %>% 
  group_by(type,method) %>%
  summarise(n = median(value,na.rm =T),.groups='keep') 

stress_genes %>% 
  group_by(type) %>%
  summarise(n = median(value,na.rm =T),.groups='keep') 

stress_genes %>% 
  group_by(method) %>%
  summarise(n = median(value,na.rm =T),.groups='keep') 
```



```{r plots}

###plot
p_method = ggplot(stress_genes, aes(x=method, y=value, fill=method)) +
  geom_boxplot(position="dodge",outlier.shape = NA) +
  ylab("mean % of cells expressing a stress-related gene")  +
  theme(axis.text.x = element_text(size=7))

p_type = ggplot(stress_genes, aes(x=type, y=value, fill=type)) +
  geom_boxplot(position="dodge",outlier.shape = NA) +
  scale_fill_manual(values = c('yellow','darkblue')) +
  ylab("")

p_patient = ggplot(stress_genes, aes(x=patient, y=value, fill=patient)) +
  geom_boxplot(position="dodge",outlier.shape = NA) +
  ylab('')
  
pdf(file.path(params$datapath,paste0("../results/Figure10_stress_genes.pdf")),width = 11,height = 6)
p_method + p_type + p_patient + plot_annotation(tag_levels = 'A')
dev.off()
```

